project_name: serverbin
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/serverbin/main.go
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "ci"
changelog:
  sort: asc
  filters:
    exclude:
      - '^style:'
      - '^docs:'
      - '^test:'
      - '^dev:'
      - '^ci:'
      - 'README.md'
      - Merge pull request
      - Merge branch
release:
  draft: true
  prerelease: true
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - marsom/serverbin:v{{ .Version }}-linux-amd64
      - ghcr.io/marsom/serverbin:v{{ .Version }}-linux-amd64
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=simple request and response service
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/amd64
  - goos: linux
    goarch: arm64
    image_templates:
      - marsom/serverbin:v{{ .Version }}-linux-arm64
      - ghcr.io/marsom/serverbin:v{{ .Version }}-linux-arm64
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=simple request and response service
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
      - --platform=linux/arm64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE