apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: serverbin
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/component: application
  app.kubernetes.io/managed-by: kubectl

resources:
  - serverbin-http.yaml
  - serverbin-tcp.yaml

images:
  - name: marsom/serverbin
    newTag: latest

