name: Build pull requests

on:
  pull_request: {}
  push:
    branches-ignore:
      - main

jobs:
  goreleaser-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.5

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.165.0
          args: -f .goreleaser.windows2019.yml --snapshot --rm-dist
  goreleaser-linux:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.5

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.169.0
          args: release --snapshot --rm-dist
