name: build

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.164.0
          args: --snapshot --rm-dist
