name: Run checks

on:
  pull_request: {}
  push:
    branches-ignore:
      - main
    tags-ignore:
      - v.*

jobs:
  go-mod:
    name: go-mod
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.4
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check module vendoring
        run: |
          go mod tidy
          go mod vendor
          git diff --exit-code || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.3
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.40.1
          skip-go-installation: true